controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: "/api/v1"

api_login_check:
    path: /api/login_check

user_register:
    resource: ../src/Controller/Inscription
    type: attribute
